backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/blog"
public_folder: "/assets/blog"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Naam van het recept", name: "title", widget: "string" }
      - { label: "Auteur", name: "author", widget: "select", options: ["Mama", "Brecht", "Justine", "Papa", "Arwen"] }
      - { label: "Categorie (laat post staan)", name: "tags", widget: "select", multiple: true, min: 2, max: 2, options: ["post", "veggie", "vegan", "vis", "vlees"], default: ["post"] }
      - label: "Ingredienten"
        name: "ingredienten"
        widget: "object"
        summary: '{{fields.name}}: {{fields.birthdate}}'
        fields:
          - {label: "Ingredient 1", name: "ingredient1", widget: "string" }
          - {label: "Ingredient 2", name: "ingredient2", widget: "string" }
          - {label: "Ingredient 3", name: "ingredient3", widget: "string" }
          - {label: "Ingredient 4", name: "ingredient4", widget: "string" }
          - {label: "Ingredient 5", name: "ingredient5", widget: "string" }
          - {label: "Ingredient 6", name: "ingredient6", widget: "string" }
      - { label: "Bereidingswijze", name: "bereidingswijze", widget: "markdown" }
      - { label: "Afbeelding", name: "image", widget: "image" }
      - { label: "Datum", name: "date", widget: "datetime" }
