backend:
  name: git-gateway
  branch: main
  repo: BrechtMatthys/mamasdagelijksekost
media_folder: "public/assets/blog"
public_folder: "/assets/blog"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Naam van het recept", name: "title", widget: "string" }
      - { label: "Auteur", name: "author", widget: "select", required: true, options: ["Mama", "Brecht", "Justine", "Papa"] }
      - { label: "Aantal personen", name: "personen", widget: "number", default: "4" }
      - { label: "Categorie (laat post staan)", name: "tags", widget: "select", multiple: true, min: 2, max: 2, options: ["post", "veggie", "vegan", "vis", "vlees", "soep", "dessert"], default: ["post"] }
      - { label: "Ingredi&#235;nten", name: "body", required: true, widget: "markdown", default: "- Item 1\n- Item 2\n- Item 3" }
      - label: "Bereidingswijze"
        name: "bereidingswijze"
        required: false
        widget: "customMarkdownEditor" 
      - { label: "Afbeelding", name: "image", required: false, widget: "image" }
      - { label: "Datum", name: "date", widget: "datetime" }

editor:
  preview: true